version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: vg_mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: vite_gourmand
      MARIADB_USER: vg_user
      MARIADB_PASSWORD: vg_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:7
    container_name: vg_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

volumes:
  mariadb_data:
  mongo_data:
